import { fetchSettings } from '@/lib/data';
import Markdown from '@/components/MarkdownRenderer';
import { notFound } from 'next/navigation';
import { getStaticPageContent, staticPageMetadata } from '@/lib/static-pages';

export async function generateMetadata() {
  const settings = await fetchSettings();
  const page = getStaticPageContent(settings, 'disclaimer', settings.pageDisclaimer, '');
  return staticPageMetadata(page);
}

export default async function Disclaimer() {
  const settings = await fetchSettings();
  const siteTitle = settings.siteTitle || 'Our Platform';
  const contactEmail = settings.contactEmail || 'contact@aipromptmatrix.in';

  const defaultContent = `
# Disclaimer

Last updated: July 6, 2026

The information provided by ${siteTitle} ("we," "us," or "our") on our website (the "Site") is for general informational purposes only. All information on the Site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.

UNDER NO CIRCUMSTANCE SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SITE OR RELIANCE ON ANY INFORMATION PROVIDED ON THE SITE. YOUR USE OF THE SITE AND YOUR RELIANCE ON ANY INFORMATION ON THE SITE IS SOLELY AT YOUR OWN RISK.

## External Links Disclaimer

The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.

WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE OR ANY WEBSITE OR FEATURE LINKED IN ANY BANNER OR OTHER ADVERTISING. WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.

## AI Generated Content Disclaimer

Our platform hosts prompts and imagery that are primarily generated by Artificial Intelligence algorithms and models. The nature of AI models means that they can be unpredictable and may generate results that are unexpected, inaccurate, offensive, or inappropriate. The text, images, and other content displayed on this Site that are generated by AI are provided "AS IS."

1. **No Guarantee of Consistency:** The images displayed are to serve as a representation of what a given prompt text might output under certain circumstances, but we do not guarantee replicability. Using the exact same prompt may yield entirely different results across different models, platforms, or even consecutive runs.
2. **Not Professional Advice:** Prompts that request code generation, legal text, medical advice, financial guidance, or other specialized professional outputs should NOT be considered as professional advice. The AI-generated output is strictly for illustrative or starting-point purposes. Always seek the advice of a qualified professional before making any decisions based on AI-generated content.
3. **Copyright and Ownership of AI Output:** The legal status of copyright for AI-generated works is currently evolving. We provide no warranty that the images or text generated from our prompts are free from copyright claims by third parties, nor do we guarantee that you can claim copyright ownership over any generated works.

## User-Generated Content Disclaimer

The Site contains content submitted by users, including prompts, comments, and images. We do not endorse to any extent any user-generated content or any opinion, recommendation, or advice expressed therein. User-generated content is the sole responsibility of the user who submitted it, and we are not liable for any errors, omissions, or any resulting harm or damages. If you believe user-submitted content infringes your rights or violates our policies, please report it via our [Contact page](/contact) or, for copyright claims, follow the process in our [DMCA Notice](/dmca).

## Trademark Disclaimer

ChatGPT, Gemini, Grok, Midjourney, Stable Diffusion, DALL·E, and all other AI tool and model names referenced on this Site are trademarks of their respective owners. ${siteTitle} is an independent platform and is not affiliated with, endorsed by, or sponsored by any of these companies. References to these tools are made solely to identify which platform a prompt is designed for.

## Errors and Omissions Disclaimer

While we strive to keep the information on the Site accurate and up to date, the AI landscape changes rapidly — models are updated, renamed, deprecated, and released frequently. Information about specific tools, model capabilities, or prompt techniques may become outdated without notice. We are under no obligation to update information that has become obsolete, and we reserve the right to change, remove, or correct any content on the Site at any time without prior notice.

## Fair Use Disclaimer

The Site may include copyrighted material the use of which has not always been specifically authorized by the copyright owner, such as screenshots or references used for commentary, criticism, education, and review. We believe this constitutes "fair use" of such material as provided for under applicable copyright law. If you wish to use any such material for purposes that go beyond fair use, you must obtain permission from the copyright owner.

## Views Expressed Disclaimer

Any views or opinions expressed on the Site — including in blog posts, guides, and comments — are personal to their authors and do not represent the views of ${siteTitle}, its staff, or its affiliates, unless explicitly stated. We are not responsible or liable for any content posted by users or third parties.

## Affiliates Disclaimer

The Site may contain links to affiliate websites, and we receive an affiliate commission for any purchases made by you on the affiliate website using such links. Affiliate relationships do not influence which prompts or tools we feature, and we aim to clearly identify sponsored or affiliate content where it appears.

## No Professional Relationship

Your use of the Site does not create any professional, advisory, fiduciary, or client relationship between you and ${siteTitle}. The Site is a content-discovery platform, not a professional services provider.

## Contact Us

If you have any questions about this Disclaimer, please contact us at ${contactEmail}.
`;
  const page = getStaticPageContent(settings, 'disclaimer', settings.pageDisclaimer, defaultContent);
  if (!page.visible) notFound();

  return (
    <div className="max-w-4xl mx-auto px-4 py-12 md:py-20 fade-in">
      <div className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-black mb-4 text-surface-900 dark:text-white">{page.title}</h1>
        <p className="text-lg text-surface-600 dark:text-surface-300 max-w-2xl mx-auto">
          {page.subtitle}
        </p>
      </div>
      <div className="bg-white dark:bg-surface-900 shadow-xl shadow-surface-200/20 dark:shadow-none border border-surface-200 dark:border-surface-800 rounded-3xl p-8 md:p-12 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-primary-500/5 blur-3xl rounded-full -translate-y-1/2 translate-x-1/2 pointer-events-none" />
        <div className="prose prose-lg dark:prose-invert max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-a:text-primary-500 hover:prose-a:text-primary-600 prose-img:rounded-2xl relative z-10">
          <Markdown>{page.body}</Markdown>
        </div>
      </div>
    </div>
  );
}
